# Generated by Django 6.0.2 on 2026-03-05 13:21

from django.db import migrations

def create_virtual_locations(apps, schema_editor):
    StockLocation = apps.get_model('stock', 'StockLocation')
    
    virtual_locations = [
        {
            'title': 'Vendors', 
            'description': 'Local virtual de origem para entrada de mercadorias. Representa o estoque em posse dos fornecedores antes do recebimento físico.',
            'slug': 'vendors',
            'is_virtual': True,
        },
        {
            'title': 'Customers', 
            'description': 'Local virtual de destino para saídas de vendas. Utilizado para equilibrar o inventário quando um produto deixa a empresa para o consumidor final.',
            'slug': 'customers',
            'is_virtual': True,
        },
        {
            'title': 'Scrap', 
            'description': 'Local de descarte para produtos avariados, vencidos ou sem condições de venda. Retira o item do estoque disponível sem gerar receita.',
            'slug': 'scrap',
            'is_virtual': True,
        },
        {
            'title': 'Inventory Loss', 
            'description': 'Local utilizado para ajustes de inventário (balanço). Registra perdas por furto, extravio ou erros de contagem identificados em auditoria.',
            'slug': 'inventory-loss',
            'is_virtual': True,
        },
        {
            'title': 'Internal Warehouse', 
            'description': 'Depósito físico principal. Representa o estoque real disponível para movimentação e venda dentro do estabelecimento.',
            'slug': 'warehouse',
            'is_virtual': False,
        },
    ]

    for loc in virtual_locations:
        StockLocation.objects.get_or_create(
            slug=loc['slug'],
            defaults={
                'title':loc['title'],
                'description':loc['description'],
                'is_virtual':loc['is_virtual'],
            }
        )

def remove_virtual_locations(apps, schema_editor):
    StockLocation = apps.get_model('stock', 'StockLocation')
    virtual_location_slugs = [ 'vendors', 'customers', 'scrap', 'inventory-loss', 'werehouse', ]
    StockLocation.objects.filter(slug__in=virtual_location_slugs).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_virtual_locations, remove_virtual_locations),
    ]
