# Generated by Django 6.0.2 on 2026-03-04 23:10

from django.db import migrations

def create_virtual_locations(apps, schema_editor):
    StockLocation = apps.get_model('stock', 'StockLocation')
    virtual_locations = [
        {
            'title': 'Customers',
            'description': 'Stock removal',
            'is_virtual': True},
        {
            'title': 'Scrap',
            'description': 'Damaged items',
            'is_virtual': True,
        },
        {
            'title': 'Inventory Loss',
            'description': 'Inventory corrections',
            'is_virtual': True,
        },
    ]

    for loc in virtual_locations:
        StockLocation.objects.get_or_create(
            defaults=loc
        )

def remove_virtual_locations(apps, schema_editor):
    StockLocation = apps.get_model('seu_app_estoque', 'StockLocation')
    StockLocation.objects.filter(is_virtual=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]
    operations = [
        migrations.RunPython(create_virtual_locations, remove_virtual_locations),
    ]
