# Generated by Django 6.0.2 on 2026-03-04 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_auto_20260304_2310"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductPriceCurrentPrice",
        ),
        migrations.AlterModelOptions(
            name="productpricehistory",
            options={"ordering": ["-created"]},
        ),
    ]
