# Generated by Django 6.0.2 on 2026-03-05 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('stock', '0002_auto_20260305_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricehistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='product',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_title',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='product.product'),
        ),
        migrations.CreateModel(
            name='MovimentFixed',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.stockmovement',),
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.movimentfixed',),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.movimentfixed',),
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.movimentfixed',),
        ),
        migrations.CreateModel(
            name='StockGain',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.movimentfixed',),
        ),
        migrations.CreateModel(
            name='StockLoss',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.movimentfixed',),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
