# Generated by Django 6.0.2 on 2026-03-07 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_defautl_virtual_locations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="target_margin",
            field=models.DecimalField(
                decimal_places=2,
                default=0.3,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(0.99),
                ],
            ),
        ),
    ]
