# Generated by Django 6.0.2 on 2026-03-06 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_stockmovement_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbalance',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
