# Generated by Django 6.0.2 on 2026-03-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_delete_unitconversion'),
        ('stock', '0007_alter_stockbalance_quantity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='quantity_gte_0'),
        ),
    ]
