# Generated by Django 6.0.2 on 2026-03-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_delete_unitconversion'),
        ('stock', '0008_stockbalance_quantity_gte_0'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='stockbalance',
            name='quantity_gte_0',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='quantity_gte_0', violation_error_message='This specific stock move already exists.'),
        ),
    ]
