# Generated by Django 6.0.2 on 2026-03-07 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0009_alter_stockbalance_quantity_gte_0"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockbalance",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(0.001)],
            ),
        ),
    ]
