FROM python:3.13-slim AS base

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    gnupg \
    build-essential \
    libpq-dev \
    git \
    cron \
    && rm -rf /var/lib/apt/lists/*


# Instala o 'uv' diretamente do binário oficial
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

# Variáveis de ambiente para o Python e uv
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1 \
    PATH="/app/.venv/bin:$PATH"

# Copia os arquivos de dependências primeiro (otimização de cache de camada)
COPY pyproject.toml uv.lock ./

# Cria o ambiente virtual e instala as dependências usando o uv
RUN uv sync --frozen --no-install-project

COPY ./entrypoint.sh /app/entrypoint.sh
COPY . .
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
