version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: prod_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: prod_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_volume:/usr/share/nginx/html/static/  # Alinhado com o caminho do seu Nginx
      - media_volume:/usr/share/nginx/html/media/    # Alinhado com o caminho do seu Nginx
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DJANGO_SETTINGS_MODULE=core.settings.prod

  nginx:  # <--- ADICIONADO AQUI
    image: nginx:alpine
    container_name: prod_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Garanta que o nome do arquivo mapeado está correto
      - static_volume:/usr/share/nginx/html/static/
      - media_volume:/usr/share/nginx/html/media/
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
