# Generated by Django 6.0.2 on 2026-06-05 12:24

from django.db import migrations

def criar_tenant_e_dominio_default(apps, schema_editor):
    Client = apps.get_model('customer', 'Client')
    Domain = apps.get_model('customer', 'Domain')

    if not Client.objects.filter(schema_name='public').exists():
        tenant_publico = Client.objects.create(
            schema_name='public',
            name='Administração Central'
        )

        Domain.objects.create(
            domain='localhost',
            tenant=tenant_publico,
            is_primary=True
        )

def reverter_tenant_e_dominio(apps, schema_editor):
    Client = apps.get_model('customer', 'Client')
    Client.objects.filter(schema_name='public').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=criar_tenant_e_dominio_default,
            reverse_code=reverter_tenant_e_dominio
        )
    ]
