# Generated by Django 6.0.2 on 2026-06-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_tenant_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='on_trial',
        ),
        migrations.RemoveField(
            model_name='client',
            name='paid_until',
        ),
    ]
