# Generated by Django 6.0.2 on 2026-03-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code_type',
            field=models.SmallIntegerField(choices=[(0, 'EAN type'), (1, 'Internal code')], default=0),
        ),
    ]
