# Generated by Django 6.0.2 on 2026-03-06 13:14

import stdnum.ean
import stdnum.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_code_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['status'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=30, unique=True, validators=[stdnum.util.isdigits, stdnum.ean.is_valid]),
        ),
    ]
