# Generated by Django 6.0.2 on 2026-03-06 13:14

from django.db import migrations

def creaate_default_unit_types(apps, schema_editor):
    UnitType = apps.get_model('product', 'UnitType')
    unit_types = [
        {
            'id': 1,
            'title': 'un',
            'description': 'Unit',
        },
        {
            'id': 2,
            'title': 'kg',
            'description': 'Kilogram',
        },
        {
            'id': 3,
            'title': 'mg',
            'description': 'Milligram',
        },
        {
            'id': 4,
            'title': 'lt',
            'description': 'Liter',
        },
        {
            'id': 5,
            'title': 'ml',
            'description': 'Milliliter',
        },
    ]
    for ut in unit_types:
        UnitType.objects.get_or_create(
            id=ut['id'],
            defaults={
                'title': ut['title'],
                'description': ut['description'],
            }
        )

def remove_default_unit_types(apps, schema_editor):
    UnitType = apps.get_model('product', 'UnitType')
    UnitType.objects.filter(pk__in=[1,2,3,4,5]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_unittype_alter_product_code'),
    ]

    operations = [
        migrations.RunPython(creaate_default_unit_types, remove_default_unit_types)
    ]
