# Generated by Django 6.0.2 on 2026-03-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_unit_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_title',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'unit_type')},
        ),
    ]
