# Generated by Django 6.0.2 on 2026-03-06 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_unique_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('factor', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='product.unittype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='product.product')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='product.unittype')),
            ],
            options={
                'unique_together': {('product', 'from_unit', 'to_unit')},
            },
        ),
    ]
