# Generated by Django 6.0.2 on 2026-03-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_unitconversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitConversion',
        ),
    ]
