# Generated by Django 6.0.2 on 2026-06-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="is_viewed",
            field=models.BooleanField(default=False),
        ),
    ]
