# Generated by Django 6.0.2 on 2026-05-08 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('company_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('company_name', models.CharField(blank=True, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('resource_slogs_visible_to_self_scheduling', models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_-]+(,[a-z0-9_-]+)*$')])),
            ],
            options={
                'ordering': ['-modified', '-created'],
                'abstract': False,
            },
        ),
    ]
