# Generated by Django 6.0.2 on 2026-05-08 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfig',
            name='resource_slogs_visible_to_self_scheduling',
        ),
        migrations.CreateModel(
            name='ResourceSlugVisible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_slug', models.SlugField()),
                ('subtitle', models.CharField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_visibles', to='app.appconfig')),
            ],
        ),
    ]
