# Generated by Django 6.0.2 on 2026-05-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceslugvisible',
            name='title',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
