# Generated by Django 6.0.2 on 2026-05-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_appconfig_resource_slogs_visible_to_self_scheduling_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appconfig',
            options={'ordering': ('status', 'created')},
        ),
        migrations.AlterUniqueTogether(
            name='resourceslugvisible',
            unique_together={('config', 'resource_slug')},
        ),
    ]
