# Generated by Django 6.0.2 on 2026-05-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_appconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='background_images/'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/'),
        ),
    ]
