# Generated by Django 6.0.2 on 2026-03-25 23:01

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_label",
                    models.CharField(
                        validators=[
                            django.core.validators.RegexValidator("^[a-z_]+\\Z")
                        ]
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        validators=[
                            django.core.validators.RegexValidator("^[a-z_]+\\Z")
                        ]
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        validators=[
                            django.core.validators.RegexValidator("^[0-9a-z_:]+\\Z")
                        ]
                    ),
                ),
                (
                    "uri",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            models.Value("uri:"),
                            "app_label",
                            models.Value(":"),
                            "model_name",
                            models.Value(":"),
                            "target_id",
                        ),
                        output_field=models.CharField(max_length=500),
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["uri"], name="uri_urimode_uri_26c631_idx")
                ],
                "unique_together": {("app_label", "model_name", "target_id")},
            },
        ),
    ]
