# Generated by Django 6.0.2 on 2026-03-17 22:47

import django.core.validators
import django.db.models.deletion
import schedule.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=1
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-modified", "-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=1
                    ),
                ),
                ("name", models.CharField()),
                (
                    "code",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("^\\d+(\\.\\d+)*$")
                        ],
                    ),
                ),
                ("is_selectable", models.BooleanField()),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="schedule.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["-modified", "-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResourceNotSelectable",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("schedule.resource",),
        ),
        migrations.CreateModel(
            name="ResourceSelectable",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("schedule.resource",),
        ),
        migrations.CreateModel(
            name="ServiceResourceRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.service",
                    ),
                ),
                (
                    "resource_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.resourcenotselectable",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="service",
            name="required_resource",
            field=models.ManyToManyField(
                through="schedule.ServiceResourceRelation",
                to="schedule.resourcenotselectable",
            ),
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=1
                    ),
                ),
                (
                    "rrule_params",
                    models.CharField(validators=[schedule.models.rrule_validator]),
                ),
                ("valid_from", models.DateField(editable=False)),
                ("valid_until", models.DateField(editable=False)),
                ("start_slot", models.PositiveSmallIntegerField(editable=False)),
                ("duration_slot", models.PositiveSmallIntegerField()),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.resourceselectable",
                    ),
                ),
            ],
            options={
                "ordering": ["-modified", "-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssignmentSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CR", "Created"),
                            ("NP", "In Progress"),
                            ("CP", "Completed"),
                            ("MG", "Migrated"),
                            ("CL", "Cancelled"),
                        ],
                        default="CR",
                        max_length=2,
                    ),
                ),
                ("date", models.DateField()),
                ("start_slot", models.PositiveSmallIntegerField()),
                ("finish_slot", models.PositiveSmallIntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.service",
                    ),
                ),
                ("resources", models.ManyToManyField(to="schedule.resourceselectable")),
            ],
            options={
                "ordering": ["-modified", "-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResourceOccupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "bitmap",
                    models.CharField(
                        max_length=288,
                        validators=[
                            django.core.validators.RegexValidator("^[0-1]+$"),
                            django.core.validators.MinLengthValidator(288),
                        ],
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.resourceselectable",
                    ),
                ),
            ],
            options={
                "unique_together": {("resource", "date")},
            },
        ),
    ]
