# Generated by Django 6.0.2 on 2026-05-31 23:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=1
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "rrule_params",
                    models.CharField(
                        validators=[
                            django.core.validators.RegexValidator(
                                "^DTSTART:{%DATE%}T\\d{6}\\nRRULE:FREQ=MINUTELY;UNTIL={%DATE%}T\\d{6}Z?;INTERVAL=\\d+;BYDAY=[A-Z]{2}(?:,[A-Z]{2})*Z"
                            )
                        ]
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
                ("time_from", models.TimeField()),
                ("time_until", models.TimeField()),
                ("duration_slot", models.PositiveSmallIntegerField()),
                ("interval_slot", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ["-modified", "-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=1
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-modified", "-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=1
                    ),
                ),
                ("name", models.CharField()),
                (
                    "code",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^([a-z0-9]+\\.)*[a-z0-9]+\\.?$"
                            )
                        ],
                    ),
                ),
                ("is_selectable", models.BooleanField()),
                ("object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("is_optional_choice", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("parent_id", "code"),
            },
        ),
        migrations.CreateModel(
            name="ResourceNotSelectable",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("schedule.resource",),
        ),
        migrations.CreateModel(
            name="ResourceObject",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("schedule.resource",),
        ),
        migrations.CreateModel(
            name="ResourcePerson",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("schedule.resource",),
        ),
        migrations.CreateModel(
            name="ResourceSelectable",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("schedule.resource",),
        ),
        migrations.CreateModel(
            name="ServiceResourceRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.service",
                    ),
                ),
                (
                    "resource_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.resourcenotselectable",
                    ),
                ),
            ],
            options={
                "unique_together": {("service", "resource_type")},
            },
        ),
        migrations.AddField(
            model_name="service",
            name="required_resources",
            field=models.ManyToManyField(
                through="schedule.ServiceResourceRelation",
                to="schedule.resourcenotselectable",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="childrens",
                to="schedule.resourcenotselectable",
            ),
        ),
        migrations.CreateModel(
            name="ResourceOccupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "bitmap",
                    models.CharField(
                        default="000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
                        max_length=288,
                        validators=[
                            django.core.validators.RegexValidator("^[0-1]+\\Z"),
                            django.core.validators.MinLengthValidator(288),
                        ],
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.resourceselectable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date", models.DateField()),
                ("start_slot", models.PositiveSmallIntegerField()),
                ("duration_slot", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PD", "Pending"),
                            ("CF", "Confirmed"),
                            ("MG", "Migrated"),
                            ("CC", "Cancelled"),
                            ("AB", "Absent"),
                            ("IP", "In Progress"),
                            ("CP", "Completed"),
                        ],
                        default="PD",
                        max_length=2,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.service",
                    ),
                ),
                ("resources", models.ManyToManyField(to="schedule.resourceselectable")),
            ],
            options={
                "ordering": ["-modified", "-created"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="schedule_re_content_23f6a9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resourceoccupation",
            unique_together={("resource", "date")},
        ),
    ]
