# Generated by Django 6.0.2 on 2026-03-17 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceoccupation",
            name="bitmap",
            field=models.CharField(
                default="000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
                max_length=288,
                validators=[
                    django.core.validators.RegexValidator("^[0-1]+$"),
                    django.core.validators.MinLengthValidator(288),
                ],
            ),
        ),
    ]
