# Generated by Django 6.0.2 on 2026-05-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set(),
        ),
    ]
