# Generated by Django 6.0.2 on 2026-06-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_auto_choice',
            field=models.BooleanField(default=False),
        ),
    ]
