# Generated by Django 6.0.2 on 2026-03-25 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
        ("uri", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="uri",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="uri.urimodel",
            ),
        ),
    ]
