# Generated by Django 6.0.2 on 2026-03-21 21:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentslot",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.service",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentslot",
            name="status",
            field=models.CharField(
                choices=[
                    ("CR", "Created"),
                    ("CF", "Confirmed"),
                    ("NP", "In Progress"),
                    ("CP", "Completed"),
                    ("MG", "Migrated"),
                    ("CL", "Cancelled"),
                ],
                default="CR",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="code",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^([a-z0-9]+\\.)*[a-z0-9]+\\.?$"
                    )
                ],
            ),
        ),
    ]
