# Generated by Django 6.0.2 on 2026-06-03 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='code',
            field=models.CharField(max_length=225, unique=True, validators=[django.core.validators.RegexValidator('^([a-z0-9]+\\.)*[a-z0-9]+\\.?$')]),
        ),
    ]
