# Generated by Django 6.0.2 on 2026-06-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_alter_resource_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="code",
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
