# Generated by Django 6.0.2 on 2026-04-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_assignment_custumer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='custumer',
            new_name='customer',
        ),
    ]
