# Generated by Django 6.0.2 on 2026-06-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_resource_is_auto_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='choice_type',
            field=models.CharField(choices=[('RFC', 'Escolha opcional pelo cliente'), ('IFC', 'Não aparece para o cliente'), ('RQC', 'Escolha obrigatoria pelo cliente')], default='RQC'),
        ),
    ]
