# Generated by Django 6.0.2 on 2026-05-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_alter_resource_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="is_optional_choice",
            field=models.BooleanField(default=False),
        ),
    ]
