# Generated by Django 6.0.2 on 2026-03-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_resource_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('CF', 'Confirmed'), ('MG', 'Migrated'), ('CC', 'Cancelled'), ('AB', 'Absent'), ('IP', 'In Progress'), ('CP', 'Completed')], default='PD', max_length=2),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
