# Generated by Django 6.0.2 on 2026-06-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_alter_resource_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
