# Generated by Django 6.0.2 on 2026-06-03 11:10

from django.db import migrations

def migrate_resource_types(apps,schema_editor):
    Resource = apps.get_model('schedule', 'Resource')

    Resource.objects.filter(
        is_optional_choice=True
    ).update(
        choice_type=Resource.ChoiceType.OPTIONAL_FOR_CLIENT.value
    )
    Resource.objects.filter(
        is_auto_choice=True
    ).update(
        choice_type=Resource.ChoiceType.INVISIBLE_FOR_CLIENT.value
    )



class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_resource_choice_type'),
    ]

    operations = [
        migrations.RunPython(migrate_resource_types)
    ]
