# Generated by Django 6.0.2 on 2026-03-28 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_assignment_status_delete_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="childrens",
                to="schedule.resourcenotselectable",
            ),
        ),
    ]
