# Generated by Django 6.0.2 on 2026-04-23 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_rename_custumer_assignment_customer'),
        ('uri', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('parent_id',)},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='customer',
        ),
        migrations.AddField(
            model_name='assignment',
            name='customer_uri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='uri.urimodel'),
        ),
    ]
