# Generated by Django 6.0.2 on 2026-03-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_resource_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='start_slot',
            new_name='interval_slot',
        ),
        migrations.AlterField(
            model_name='availability',
            name='valid_until',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
