# Generated by Django 6.0.2 on 2026-06-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20260603_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='choice_type',
            field=models.CharField(choices=[('RQC', 'Escolha obrigatoria pelo cliente'), ('RFC', 'Escolha opcional pelo cliente'), ('IFC', 'Não aparece para o cliente')], default='RQC'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_auto_choice',
            field=models.GeneratedField(db_persist=True, expression=models.ExpressionWrapper(models.Q(('choice_type', 'IFC')), output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_optional_choice',
            field=models.GeneratedField(db_persist=True, expression=models.ExpressionWrapper(models.Q(('choice_type', 'RFC')), output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
    ]
