# Generated by Django 6.0.2 on 2026-04-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0004_alter_resource_options_remove_assignment_customer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="customer_uri",
        ),
    ]
