# Generated by Django 6.0.2 on 2026-05-08 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schedule', '0005_remove_assignment_customer_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='uri',
        ),
        migrations.AddField(
            model_name='resource',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='resource',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['content_type', 'object_id'], name='schedule_re_content_23f6a9_idx'),
        ),
    ]
