# Generated by Django 6.0.2 on 2026-03-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_rename_start_slot_availability_interval_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='interval_slot',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='valid_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
