# Generated by Django 6.0.2 on 2026-05-13 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_remove_resource_uri_resource_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceresourcerelation',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
