# Generated by Django 6.0.2 on 2026-04-06 11:47

import django.core.validators
import schedule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_availability_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='rrule_params',
            field=models.CharField(validators=[django.core.validators.RegexValidator('^DTSTART:{%DATE%}T\\d{6}\\nRRULE:FREQ=MINUTELY;UNTIL={%DATE%}T\\d{6}Z?;INTERVAL=\\d+;BYDAY=[A-Z]{2}(?:,[A-Z]{2})*Z'), schedule.models.rrule_validator]),
        ),
    ]
