# Generated by Django 6.0.2 on 2026-05-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_serviceresourcerelation_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('parent_id', 'code')},
        ),
    ]
