# Generated by Django 6.0.2 on 2026-04-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_availability_rrule_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='resource',
        ),
    ]
