# Generated by Django 6.0.2 on 2026-05-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schedule', '0008_alter_resource_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceObject',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('schedule.resource',),
        ),
        migrations.CreateModel(
            name='ResourcePerson',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('schedule.resource',),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('content_type', 'object_id')},
        ),
    ]
