# Generated by Django 6.0.2 on 2026-06-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="whatsapp_phone",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
