# Generated by Django 6.0.2 on 2026-06-06 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_customuser_whatsapp_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="whatsapp_phone",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^\\+?1?\\d{9,15}$")
                ],
            ),
        ),
    ]
