# Generated by Django 6.0.2 on 2026-06-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_emaillog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailLog',
        ),
    ]
