# Generated by Django 6.0.2 on 2026-03-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0002_alter_transaction_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="account_type",
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="sale.accountselectable"
            ),
        ),
    ]
