# Generated by Django 6.0.2 on 2026-03-07 16:08

from django.db import migrations

def create_market_chart_of_accounts(apps, schema_editor):
    Account = apps.get_model('sale', 'Account')

    chart_data = [
        ('1', 'ASSETS', False, None),
        ('2', 'LIABILITIES', False, None),
        ('3', 'EQUITY', False, None),
        ('4', 'REVENUE', False, None),
        ('5', 'EXPENSES', False, None),

        ('1.1', 'CASH AND CASH EQUIVALENTS', False, '1'),
        ('1.2', 'INVENTORIES', False, '1'),
        ('2.1', 'CURRENT LIABILITIES', False, '2'),
        ('4.1', 'SALES REVENUE', False, '4'),
        ('5.1', 'COST OF SALES', False, '5'),
        ('5.2', 'OPERATING EXPENSES', False, '5'),

        ('1.1.01', 'PETTY CASH', True, '1.1'),
        ('1.1.02', 'CASH IN BANK', True, '1.1'),
        ('1.1.03', 'ACCOUNTS RECEIVABLE - CARDS', True, '1.1'),
        ('1.2.01', 'MERCHANDISE FOR RESALE', True, '1.2'),
        ('2.1.01', 'ACCOUNTS PAYABLE - VENDORS', True, '2.1'),
        ('2.1.02', 'TAXES PAYABLE (IBS/CBS)', True, '2.1'),
        ('4.1.01', 'RETAIL SALES REVENUE', True, '4.1'),
        ('5.1.01', 'COGS - COST OF GOODS SOLD', True, '5.1'),
        ('5.2.01', 'RENT AND UTILITIES', True, '5.2'),
        ('5.2.02', 'LOSSES AND SHRINKAGE', True, '5.2'),
    ]

    for code, name, selectable, parent_code in chart_data:
        parent_obj = None
        if parent_code:
            parent_obj = Account.objects.get(code=parent_code)
        
        Account.objects.get_or_create(
            code=code,
            defaults={
                'name': name.upper(),
                'is_selectable': selectable,
                'parent': parent_obj
            }
        )

def rollback_chart_of_accounts(apps, schema_editor):
    Account = apps.get_model('sale', 'Account')
    Account.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0003_remove_account_account_type_and_more"),
    ]

    operations = [
        migrations.RunPython(create_market_chart_of_accounts, rollback_chart_of_accounts)
    ]
